### ISSUE TITLE
Ruby mimetype

### ISSUE THREAD

**Issue by Demonstrandum** [flipflop97/Mato#33]
I see CSS, JavaScript, Python, etc. but no ruby, crystal, elixir or Erlang file. Perhaps some good file icons to add?

 - [x] Ruby (`application/x-ruby`)
 - [ ] Crystal  (`???`)
 - [ ] Elixir  (`???`)
 - [x] Erlang (`text/x-erlang`)

**Comment by flipflop97** [comment]
Crystal and Elixir filetypes don't have a unique mimetype associated on my system, they appear as plain text files (`text/plain`). Do they have a unique mimetype on your system? If not, they can't be added to the icon pack unfortunately.

**Comment by Demonstrandum** [comment]
I don't have many mimetypes, `.html` correctly identifies as `text/html` but things like Python or JS, don't:
```shell
file --mime-type hello.py 
hello.py: text/plain

file --mime-type test.js 
test.js: text/plain
```
I have added a few mimetypes manually in the past though.

I often see icon packs adding icons with this system: https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html

You'd add an icon to the new mimetype:
```shell
xdg-icon-resource install --context mimetypes --size 48 elixir-file-icon.png x-application-elixir
```

An xml file to describe it, e.g. 
```xml
<?xml version="1.0"?>
 <mime-info xmlns='http://www.freedesktop.org/standards/shared-mime-info'>
   <mime-type type="application/x-elixir">  
   <comment>Elixir File</comment>
   <comment xml:lang="...">...</comment>
   <glob pattern="*.ex"/>
  </mime-type>
 </mime-info>
```
And install that with `xdg-mime install elixir-file.xml`

I understand if you don't want to do this, but it could be a way of supporting more icons.

**Comment by flipflop97** [comment]
I'm aware of the possibility to add mimetypes, but that seems like a separate project (I wouldn't be surprised if there's already a project to add additional mimetypes). So this icon pack won't add any itself.

Also, you might want to use the following command instead of the one you're using. It supports way more mime types (including the custom ones) and is used by gnome to display the right icons.
```bash
xdg-mime query filetype filename.ext
```

**Comment by Demonstrandum** [comment]
So there is a possibility of integrating or using some project with support for more mimetypes, in the future?

**Comment by flipflop97** [comment]
Well if you can find the official mimetype strings for these files and find them being used somewhere, feel free to make a new issue and I'll gladly add them. I won't add icons for unused mimetypes that nobody is seeing anyway.

**Comment by Demonstrandum** [comment]
Here, [mimetype-xml](https://github.com/Demonstrandum/mimetype-xml) you can add the mimetypes for file mimetypes that don't exist on your system and most likely not on others (not to say they aren't popular)

Just edit a TOML config file like so
```toml
[x-application-elixir]
type = "application/x-elixir"
pattern = ["*.ex", "*.exs"]
comment = "Elixir File"
comment_lang = [ ["no", "Elixir Fil"], ["la", "Ordo Elixir"] ]
icon = "mimetype/application-x-elixir.svg"
size = 128 # Needed, but does not apply to SVGs

[x-application-toml]
type = "application/x-toml"
pattern = ["*.toml"]
comment = "TOML File"
icon = "mimetype/application-x-toml.svg"
size = 128
```
and run a ruby script for it
```ruby
require 'mimetype_xml'
require 'toml' # `toml` comes with this gem (`mimetype_xml`)

xml = MimetypeXML::Generate.toml_file(
  :file      => './custom-mime.toml', # The location of the TOML config
  :xml_dir   => '/usr/share/mime/packages/', # Make sure the dir is writable for the user, run `sudo chmod 777 /usr/share/mime/packages/`
  :icon_pack => '~/.icons/Mato'
)
files = xml.write_files
files.install
```
I've made a fork that already does all of this, [Demonstrandum/Mato](https://github.com/Demonstrandum/Mato) and you can add anything quickly to the toml config and re-run the `./install.sh` script that has been modified to work with this.

Can I send a pull request?
